name: Create and Upload Release

# on:
#   push:
#     tags:
#       - "v*" # Triggers on tags like v1.0, v1.1, etc.

on:
  release:
    types: [created] # This triggers when a release is created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build the package
        run: |
          python setup.py sdist

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/pdfmirror-0.1.0.tar.gz
          asset_name: pdfmirror-0.1.0.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
